In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[
    'I love my country',
    'I love my city',
    'the glass of water is full',
    'the glass of water is empty',
    'I am a good boy'
]

In [4]:
voc_size=10000

onehot_repr=[one_hot(words,voc_size) for words in sent]
onehot_repr

[[2450, 4523, 1389, 734],
 [2450, 4523, 1389, 8268],
 [8936, 7768, 1259, 5644, 45, 6106],
 [8936, 7768, 1259, 5644, 45, 8823],
 [2450, 1480, 4140, 943, 2487]]

In [5]:
#word emading representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [6]:
import numpy as np


In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2450 4523 1389  734]
 [   0    0    0    0 2450 4523 1389 8268]
 [   0    0 8936 7768 1259 5644   45 6106]
 [   0    0 8936 7768 1259 5644   45 8823]
 [   0    0    0 2450 1480 4140  943 2487]]


In [9]:
#feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [10]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step


array([[[ 0.01685048, -0.0041257 , -0.02226426,  0.04113745,
          0.00773195,  0.02713526,  0.0426852 ,  0.03185115,
         -0.01980497, -0.01789763],
        [ 0.01685048, -0.0041257 , -0.02226426,  0.04113745,
          0.00773195,  0.02713526,  0.0426852 ,  0.03185115,
         -0.01980497, -0.01789763],
        [ 0.01685048, -0.0041257 , -0.02226426,  0.04113745,
          0.00773195,  0.02713526,  0.0426852 ,  0.03185115,
         -0.01980497, -0.01789763],
        [ 0.01685048, -0.0041257 , -0.02226426,  0.04113745,
          0.00773195,  0.02713526,  0.0426852 ,  0.03185115,
         -0.01980497, -0.01789763],
        [-0.00777727, -0.02367663, -0.04468043, -0.02077444,
         -0.02567064,  0.03780473,  0.00865819, -0.04077847,
         -0.02798656, -0.0470642 ],
        [ 0.03342668, -0.0292163 ,  0.01096056,  0.01516146,
          0.03926129,  0.02513951,  0.01281111, -0.04967461,
          0.04232221,  0.02094007],
        [ 0.00354246,  0.00141597, -0.03963454,  0.0

In [ ]:
i